// dashboard.model.ts
export interface StudentAttendanceData {
  totalStudents?: number;
  attendance?: {
    Present: number[];
    Absent: number[];
    Late: number[];
  };
  categories?: string[];
  classAttendance?: {
    Present: number;
    Absent: number;
    Late: number;
  };
  overallAttendance?: {
    Present: number;
    Absent: number;
    Late: number;
  };
}

export interface TeacherDashboardData {
  totalTeachers?: number;
  presentToday?: number;
  absentToday?: number;
  onLeaveToday?: number;
  pendingLeaveRequests?: number;
  autoGeneratedAbsences?: number;
  averageLeaveBalance?: number;
  isHoliday?: boolean;
}

export interface FeeSummary {
  totalRemainingDue?: number;
  totalPaid?: number;
  overdueCount?: number;
  collectionRate?: number;
  invoiceCount?: number;
}

export interface ClassBreakdown {
  _id?: string;
  className?: string;
  invoiceCount?: number;
  totalAmount?: number;
  totalPaid?: number;
  totalRemainingDue?: number;
  overdueCount?: number;
  collectionRate?: number;
}

export interface PaymentMethod {
  method?: string;
  totalAmount?: number;
}

export interface TopDefaulter {
  _id?: string;
  studentName?: string;
  admissionNo?: string;
  className?: string;
  remainingDue?: number;
  parentPhone:any;
  dueMonths:any;
}

export interface MonthlyTrend {
  month?: string;
  totalPaid?: number;
  totalRemainingDue?: number;
}

export interface AcademicYear {
  _id?: string;
  name?: string;
  startDate?: string;
  endDate?: string;
}

export interface Class {
  _id?: string;
  name?: string;
}

export interface AnalyticEcommerce {
  title: string;
  amount: string;
  background: string;
  border: string;
  icon: string;
  percentage: string;
  color: string;
  number: string;
}

export interface Transaction {
  background: string;
  icon: string;
  title: string;
  time: string;
  amount: string;
  percentage: string;
}

export interface FeeDashboardData {
  summary: FeeSummary;
  totalDefaultersCount:number;
  breakdownByClass: ClassBreakdown[];
  paymentMethods: PaymentMethod[];
  topDefaulters: TopDefaulter[];
  monthlyTrend: MonthlyTrend[];
}